// <auto-generated />
using System;
using MeetingMinutesAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingMinutesAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeetingMinutesDbContext))]
    [Migration("20260905194333_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ActionItemEvidence", b =>
                {
                    b.Property<Guid>("MinutesActionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesActionItemId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("ActionItemEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("AudioFiles", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedSegmentSource", b =>
                {
                    b.Property<Guid>("CleanedTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CleanedTranscriptSegmentId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("CleanedSegmentSources", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("CleanedTranscripts", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CleanedTranscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CleanedTranscriptId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("CleanedTranscriptId", "Position")
                        .IsUnique();

                    b.ToTable("CleanedTranscriptSegments", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.DecisionEvidence", b =>
                {
                    b.Property<Guid>("MinutesDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesDecisionId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("DecisionEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProcessingErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessingErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Meetings", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DateText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("MeetingId", "Kind")
                        .IsUnique();

                    b.ToTable("MeetingMinutes", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assignee")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Deadline")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesActionItems", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesDecisions", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesOpenQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesOpenQuestions", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesParticipants", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesTopics", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesUncertainty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MeetingMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingMinutesId", "Position")
                        .IsUnique();

                    b.ToTable("MinutesUncertainties", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.OpenQuestionEvidence", b =>
                {
                    b.Property<Guid>("MinutesOpenQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesOpenQuestionId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("OpenQuestionEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ParticipantEvidence", b =>
                {
                    b.Property<Guid>("MinutesParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesParticipantId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("ParticipantEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("ErrorRetryable")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("TotalDurationMilliseconds")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("MeetingId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ProcessingRuns", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ProcessingStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActualProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("FallbackReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId", "Stage")
                        .IsUnique();

                    b.ToTable("ProcessingStages", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.RawTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("RawTranscripts", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EndMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("RawTranscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speaker")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("StartMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RawTranscriptId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("RawTranscriptId", "Position")
                        .IsUnique();

                    b.ToTable("RawTranscriptSegments", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.TopicEvidence", b =>
                {
                    b.Property<Guid>("MinutesTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesTopicId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("TopicEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.UncertaintyEvidence", b =>
                {
                    b.Property<Guid>("MinutesUncertaintyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawTranscriptSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MinutesUncertaintyId", "RawTranscriptSegmentId");

                    b.HasIndex("RawTranscriptSegmentId");

                    b.ToTable("UncertaintyEvidence", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ActionItemEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesActionItem", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.AudioFile", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.Meeting", null)
                        .WithOne("AudioFile")
                        .HasForeignKey("MeetingMinutesAI.Domain.Meetings.AudioFile", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedSegmentSource", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.CleanedTranscriptSegment", null)
                        .WithMany("Sources")
                        .HasForeignKey("CleanedTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscript", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.Meeting", null)
                        .WithOne("CleanedTranscript")
                        .HasForeignKey("MeetingMinutesAI.Domain.Meetings.CleanedTranscript", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscriptSegment", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.CleanedTranscript", null)
                        .WithMany("Segments")
                        .HasForeignKey("CleanedTranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.DecisionEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesDecision", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.Meeting", null)
                        .WithMany("Minutes")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesActionItem", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesDecision", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("Decisions")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesOpenQuestion", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("OpenQuestions")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesParticipant", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("Participants")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesTopic", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("Topics")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesUncertainty", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", null)
                        .WithMany("Uncertainties")
                        .HasForeignKey("MeetingMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.OpenQuestionEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesOpenQuestion", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesOpenQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ParticipantEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesParticipant", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ProcessingRun", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.Meeting", null)
                        .WithMany("ProcessingRuns")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ProcessingStage", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.ProcessingRun", null)
                        .WithMany("Stages")
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.RawTranscript", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.Meeting", null)
                        .WithOne("RawTranscript")
                        .HasForeignKey("MeetingMinutesAI.Domain.Meetings.RawTranscript", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscript", null)
                        .WithMany("Segments")
                        .HasForeignKey("RawTranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.TopicEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesTopic", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.UncertaintyEvidence", b =>
                {
                    b.HasOne("MeetingMinutesAI.Domain.Meetings.MinutesUncertainty", null)
                        .WithMany("Evidence")
                        .HasForeignKey("MinutesUncertaintyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingMinutesAI.Domain.Meetings.RawTranscriptSegment", "RawSegment")
                        .WithMany()
                        .HasForeignKey("RawTranscriptSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RawSegment");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscript", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.CleanedTranscriptSegment", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.Meeting", b =>
                {
                    b.Navigation("AudioFile");

                    b.Navigation("CleanedTranscript");

                    b.Navigation("Minutes");

                    b.Navigation("ProcessingRuns");

                    b.Navigation("RawTranscript");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MeetingMinutes", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Decisions");

                    b.Navigation("OpenQuestions");

                    b.Navigation("Participants");

                    b.Navigation("Topics");

                    b.Navigation("Uncertainties");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesActionItem", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesDecision", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesOpenQuestion", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesParticipant", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesTopic", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.MinutesUncertainty", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.ProcessingRun", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MeetingMinutesAI.Domain.Meetings.RawTranscript", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
